import { Button, Space, Table } from 'antd'
import React from 'react'
import useAntdTable from '../../hooks/useAntdTable'

function Manage() {
    const PAGE_SHOW_COLUMN_LIST = [
        {
            "GROUP_NAME": "",
            "KEY": "key",
            "NAME": "序号",
            render: (text, record) => {
                return <a href='_blank'>{text + 1}</a>
            },
            columnProps: {
                width: '100px',
                align: 'left'
            }
        },
        {
            "GROUP_NAME": "",
            "KEY": "CONFIG_CODE",
            "NAME": "配置编码",
            render: (text, record) => {
                return <Button type='primary' onClick={() => console.log(tableDataController)}>{text}</Button>
            }
        },
        {
            "GROUP_NAME": "",
            "KEY": "ORDER_CHNL_NAME",
            "NAME": "订单接口渠道",
            render: (text, record) => {
                return <div>
                    <div>{text}</div>
                    <div>触点编码:{record.CHANNEL_CODE || '-'}</div>
                    <div>产品编码:{record.CUCC_GOODS_ID || '-'}</div>
                </div>
            }
        },
        {
            "GROUP_NAME": "",
            "KEY": "CHANNEL_CODE",
            "NAME": "触点编码"
        },
        {
            "GROUP_NAME": "",
            "KEY": "CUCC_GOODS_ID",
            "NAME": "产品编码"
        },
        {
            "GROUP_NAME": "",
            "KEY": "PROVINCE_NAME",
            "NAME": "号码省份"
        },
        {
            "GROUP_NAME": "",
            "KEY": "EPARCHY_NAME",
            "NAME": "号码地市"
        },
        {
            "GROUP_NAME": "",
            "KEY": "SEND_PROVINCE_NAME",
            "NAME": "配送省份"
        },
        {
            "GROUP_NAME": "",
            "KEY": "SEND_EPARCHY_NAME",
            "NAME": "配送地市"
        },
        {
            "GROUP_NAME": "",
            "KEY": "PRIORITY",
            "NAME": "优先级"
        },
        {
            "GROUP_NAME": "",
            "KEY": "DISABLED_NAME",
            "NAME": "状态"
        },
        {
            "GROUP_NAME": "",
            "KEY": "action",
            "NAME": "操作",
            render: (_, record) => <Space direction='vertical'>
                <Button type="link" onClick={() => tableDataController.search(1)}>刷新当前页</Button>
                <Button type="link" onClick={() => tableDataController.loadPage(1)}>刷新第一页</Button>
            </Space>
        }
    ]
    const data = {
        "desc": "成功",
        "err": 0,
        "list": [
            {
                "CHANNEL_CODE": "08-2278-3840-a2nm",
                "CONFIG_CODE": "CU2022062300252",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "90721153",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "170",
                "EPARCHY_NAME": "济南",
                "ID": 256,
                "ORDER_CHNL_CODE": "CHNLCUCCSD001",
                "ORDER_CHNL_NAME": "CHNLCUCCSD001|山东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "17",
                "PROVINCE_NAME": "山东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "460000",
                "SEND_PROVINCE_NAME": "海南",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afib-aioo",
                "CONFIG_CODE": "CU2022062300508",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 512,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "520000",
                "SEND_PROVINCE_NAME": "贵州",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afic-aiov",
                "CONFIG_CODE": "CU2022062300764",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 768,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "540000",
                "SEND_PROVINCE_NAME": "西藏",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afib-aioh",
                "CONFIG_CODE": "CU2022062301020",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 1024,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "230000",
                "SEND_PROVINCE_NAME": "黑龙江",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afia-aio9",
                "CONFIG_CODE": "CU2022062301276",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 1280,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "420000",
                "SEND_PROVINCE_NAME": "湖北",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afig-aip5",
                "CONFIG_CODE": "CU2022062301532",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 1536,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "530000",
                "SEND_PROVINCE_NAME": "云南",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afif-aipg",
                "CONFIG_CODE": "CU2022062301788",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 1792,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "110000",
                "SEND_PROVINCE_NAME": "北京",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afie-aips",
                "CONFIG_CODE": "CU2022062302044",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 2048,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "310000",
                "SEND_PROVINCE_NAME": "上海",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afid-aiq4",
                "CONFIG_CODE": "CU2022062302300",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 2304,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "430000",
                "SEND_PROVINCE_NAME": "湖南",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afid-aipw",
                "CONFIG_CODE": "CU2022062302556",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 2560,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "610000",
                "SEND_PROVINCE_NAME": "陕西",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afii-aiqr",
                "CONFIG_CODE": "CU2022062302812",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 2816,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "120000",
                "SEND_PROVINCE_NAME": "天津",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-aemq-aj23",
                "CONFIG_CODE": "CU2022062303068",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "152",
                "EPARCHY_NAME": "威海",
                "ID": 3072,
                "ORDER_CHNL_CODE": "CHNLCUCCSD001",
                "ORDER_CHNL_NAME": "CHNLCUCCSD001|山东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "17",
                "PROVINCE_NAME": "山东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "120000",
                "SEND_PROVINCE_NAME": "天津",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-aemq-ajct",
                "CONFIG_CODE": "CU2022062303324",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "166",
                "EPARCHY_NAME": "青岛",
                "ID": 3328,
                "ORDER_CHNL_CODE": "CHNLCUCCSD001",
                "ORDER_CHNL_NAME": "CHNLCUCCSD001|山东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "17",
                "PROVINCE_NAME": "山东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "150000",
                "SEND_PROVINCE_NAME": "内蒙古",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-aemq-ajd2",
                "CONFIG_CODE": "CU2022062303580",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "166",
                "EPARCHY_NAME": "青岛",
                "ID": 3584,
                "ORDER_CHNL_CODE": "CHNLCUCCSD001",
                "ORDER_CHNL_NAME": "CHNLCUCCSD001|山东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "17",
                "PROVINCE_NAME": "山东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "620000",
                "SEND_PROVINCE_NAME": "甘肃",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07",
                "CONFIG_CODE": "CU2022062303836",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "530",
                "EPARCHY_NAME": "佛山",
                "ID": 3840,
                "ORDER_CHNL_CODE": "CHNLCUCCGD001",
                "ORDER_CHNL_NAME": "CHNLCUCCGD001|广东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "51",
                "PROVINCE_NAME": "广东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "520000",
                "SEND_PROVINCE_NAME": "贵州",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07",
                "CONFIG_CODE": "CU2022062304092",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "ZZZZZZ",
                "EPARCHY_NAME": "不区分",
                "ID": 4096,
                "ORDER_CHNL_CODE": "CHNLCUCCHEN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHEN001|河南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "76",
                "PROVINCE_NAME": "河南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "640000",
                "SEND_PROVINCE_NAME": "宁夏",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "01-4355-aemu-aie5",
                "CONFIG_CODE": "CU2022062304348",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "540",
                "EPARCHY_NAME": "深圳",
                "ID": 4352,
                "ORDER_CHNL_CODE": "CHNLCUCCGD001",
                "ORDER_CHNL_NAME": "CHNLCUCCGD001|广东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "51",
                "PROVINCE_NAME": "广东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "150000",
                "SEND_PROVINCE_NAME": "内蒙古",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "08-2278-3840-a2nm",
                "CONFIG_CODE": "CU2022062300253",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "90721153",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "170",
                "EPARCHY_NAME": "济南",
                "ID": 257,
                "ORDER_CHNL_CODE": "CHNLCUCCSD001",
                "ORDER_CHNL_NAME": "CHNLCUCCSD001|山东联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "17",
                "PROVINCE_NAME": "山东",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "510000",
                "SEND_PROVINCE_NAME": "四川",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afib-aioo",
                "CONFIG_CODE": "CU2022062300509",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 513,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "530000",
                "SEND_PROVINCE_NAME": "云南",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            },
            {
                "CHANNEL_CODE": "07-4355-afic-aiou",
                "CONFIG_CODE": "CU2022062300765",
                "CREATE_DATE": 1655973605000,
                "CREATE_DATE_STR": "2022-06-23 16:40:05",
                "CREATE_PERSON": "STF2019122000001",
                "CREATE_PERSON_NAME": "唐依妹",
                "CUCC_GOODS_ID": "91215527",
                "DISABLED": "0",
                "DISABLED_NAME": "有效",
                "EPARCHY_CODE": "741",
                "EPARCHY_NAME": "长沙",
                "ID": 769,
                "ORDER_CHNL_CODE": "CHNLCUCCHUN001",
                "ORDER_CHNL_NAME": "CHNLCUCCHUN001|湖南联通接口渠道",
                "PRIORITY": 10,
                "PROVINCE_CODE": "74",
                "PROVINCE_NAME": "湖南",
                "SEND_EPARCHY_CODE": "ZZZZZZ",
                "SEND_EPARCHY_NAME": "不区分",
                "SEND_PROVINCE_CODE": "110000",
                "SEND_PROVINCE_NAME": "北京",
                "UPDATE_DATE": 1655973605000,
                "UPDATE_DATE_STR": "2022-06-23 16:40:05",
                "UPDATE_PERSON": "STF2019122000001",
                "UPDATE_PERSON_NAME": "唐依妹"
            }
        ],
        "page": {
            "beginNo": 0,
            "nowPage": 1,
            "pageCount": 226,
            "rowTop": 4503,
            "rowsPage": 20
        }
    }

    const tableDataController = useAntdTable(
        (nextPage, pageSize) => {
            return new Promise((resolve, reject) => {
                console.log('nextPage', nextPage);
                console.log('pageSize', pageSize);
                let result = { ...data, list: [...data.list], page: { ...data.page } }
                if (pageSize) result.page.rowsPage = pageSize
                if (pageSize === 10) result.list.length = 10
                if (pageSize === 20) result.list.length = 20
                resolve(result)
            })
        },
        PAGE_SHOW_COLUMN_LIST,
        { initNotLoad: false, showSizeChanger: true }
    )

    return (
        <div style={{ margin: '20px' }}>
            <Button type='primary' onClick={() => tableDataController.search()}>查询</Button>
            <Table {...tableDataController} />
        </div>
    )
}

export default Manage